version: '3.1'
services:
  db:
    hostname: db
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - PORT=8000
      - SECRET_KEY = "django-insecure-w0qy(&fxbwdb9chfahk56t6#2jee-lf6je!$49+hy!mj#%a9@p"
      - MDB_HOST_DEV= mongodb://db:27017
      - MDB_HOST_PROD = mongodb+srv://omanohar15:Kalwa1234@cluster0.8fwyk9q.mongodb.net/test&retryWrites=true&w=majority
      - MDB_NAME_DEV = Electricity_bill
      - KALWA_USERNAME='kalwacctv'
      - KALWA_PASSWORD='Kalwa@1234'
    depends_on:
      - db