# Generated by Django 4.1.7 on 2023-03-28 19:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_no', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('bill_amount', models.FloatField()),
                ('due_date', models.DateField()),
                ('incentive_due_date', models.DateField()),
                ('incentive_amount', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('units_consumed', models.FloatField()),
                ('bill_desc', models.CharField(max_length=100)),
                ('connection_category', models.CharField(default='', max_length=50)),
                ('connection_type', models.CharField(default='', max_length=50)),
                ('region', models.CharField(default='', max_length=50)),
                ('electrical_duty', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillUnit',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaultBill',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fault_reason', models.CharField(max_length=100)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_app.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillMeter',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer_no', models.CharField(max_length=100)),
                ('billing_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_app.billunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_app.billmeter'),
        ),
    ]
