# Generated by Django 4.1.7 on 2023-03-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_no',
        ),
    ]
