# Generated by Django 3.2 on 2023-03-30 05:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('voucher_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('incentive_amount', models.FloatField(default=models.FloatField())),
                ('unit', models.IntegerField()),
                ('voucher_desc', models.CharField(max_length=50)),
                ('voucher_date', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('last_bill_date', models.DateField()),
                ('bills', models.ManyToManyField(to='bill_app.Bill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
