# Generated by Django 3.2 on 2023-04-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='cleared_bills',
            field=models.ManyToManyField(blank=True, related_name='cleared_bills', to='bill_app.Bill'),
        ),
    ]
