# Generated by Django 4.1.7 on 2023-03-29 02:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0002_remove_bill_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultbill',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fault_bill', to='bill_app.bill'),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('incentive_amount', models.FloatField(default=models.FloatField())),
                ('unit', models.IntegerField()),
                ('voucher_desc', models.CharField(max_length=50)),
                ('voucher_date', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('last_bill_date', models.DateField()),
                ('bills', models.ManyToManyField(to='bill_app.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
