# Generated by Django 4.1.7 on 2023-03-29 03:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0003_alter_faultbill_bill_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill_amount',
            new_name='amount',
        ),
        migrations.CreateModel(
            name='RecieptFile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reciept_file', models.FileField(blank=True, null=True, upload_to='reciept_files/')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reciept_file', to='bill_app.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
