# Generated by Django 3.2 on 2023-04-15 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0003_remove_voucher_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-bill_date']},
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('bill_meter', 'bill_date','amount')},
        ),
    ]
